import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/header";
import Nav from "./components/nav";
import "swiper/css";
import "swiper/css/pagination";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-4">{children}</div>
      </body>
    </html>
  );
}
